apiVersion: v1
kind: Service
metadata:
  name: authcore-api
  namespace: authcore
  labels:
    app: authcore-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 4000
    protocol: TCP
    name: https
  selector:
    app: authcore-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

